config/routes.rb
Rails.application.routes.draw do
  resources :about, only: [:index]
  
  resources :lists, only: [] do
    member do
      patch :move
    end
  end
  resources :cards, only: [:create, :update] do
    member do
      patch :move
    end
  end
  resources :boards do
    resources :lists, shallow: true, only: [:create, :destroy] do
      resources :cards, shallow: true, only: [:destroy] do
        # resources :notes, shallow: true, only: [:create, :destroy, :update]
        # resources :tasks, shallow: true, only: [:create, :destroy, :update]
      end
    end
  end
  resources :people

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/client/', to: "client#index", via: :all
  match '/client/*path', to: "client#index", via: :all

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :boards do
        resources :lists, only: [:create, :destroy, :update]
      end
      resources :users, only: [:index, :show,:create,:destroy]
      resources :tokens, only: [:create]
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  acts_as_list scope: :board

  belongs_to :board
  has_many :cards, -> { order(position: :asc, updated_at: :desc)}, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  # mount_uploader :image, ImageUploader

  scope :sorted, -> { order(position: :asc, updated_at: :desc)}
  validates :name, presence: true
end

app/controllers/api/v1/list_controller.rb
class Api::V1::ListsController < Api::ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:create]
  before_action :set_list, :authorize_user!, except: [:create]

  def index
    @lists = current_user.board.lists.order(order: :asc, created_at: :desc)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.board = @board
    if @list.save
      render json: { message: 'List was created', @list }
    else
      render json: { message: 'List was not created',  @list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      render json: { message: 'List was updated', @list }
    else
      render json: { message: 'List was not updated',  @list.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    if @list.destroy
      head :ok
      render json: { message: 'List was successfully deleted' }
    else
      head :bad_request
      render json: { message: 'List was not deleted' }
    end
  end

  private
  def set_list
    @list = List.friendly.find(params[:id])
  end

  def set_board
    @board = Board.friendly.find(params[:board_id])
    unless can?(:crud, @board)
      render json: { message: 'You cannot manage this board and its lists',  @board.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def list_params
    params.require(:list).permit(:name, :position, :background_color, :image, :status, :slug, :board_id)
  end

  def authorize_user!
    unless can?(:crud, @list)
      render json: { message: 'You cannot manage lists',  @list.errors.full_messages }, status: :unprocessable_entity
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:create]
  before_action :set_list, :authorize_user!, except: [:create]

  def index
    @lists = current_user.lists.sorted
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    @list.board = @board

    respond_to do |format|
      if @list.save

        ActionCable.server.broadcast "board", { commit: 'addList', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to board_path(@board), notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { redirect_to board_path(@board), notice: 'List not created.' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @board, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to @list.board, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    # act_as_list have the method insert_at that Change the Position and Reoder the List
    @list.insert_at(list_params[:position].to_i)
    ActionCable.server.broadcast "board", { commit: 'moveList', payload: render_to_string(:show, format: :json) }
    render action: :show
  end

  private
  def set_list
    @list = List.friendly.find(params[:id])
  end

  def set_board
    @board = Board.friendly.find(params[:board_id])
    unless can?(:crud, @board)
      flash[:alert] = "You cannot 'crud' lists!"
      redirect_to board_path(@board)
    end
  end

  def list_params
    params.require(:list).permit(:name, :position, :background_color, :image, :status, :slug, :board_id)
  end

  def authorize_user!
    unless can?(:crud, @list)
      flash[:alert] = "You cannot 'crud' lists!"
      redirect_to board_path(@list.board)
    end
  end
end

app/views/lists/_form.html.erb
<%= semantic_form_for @list do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :position %>
    <%= f.input :background_color %>
    <%= f.input :image, :as => :file %>
    <%= f.input :status %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
    <%= f.action :cancel, :as => :link %>
  <% end %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Position</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.board.name %></td>
        <td><%= list.position %></td>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @list.position %>
</p>

<p>
  <strong>Background color:</strong>
  <%= @list.background_color %>
</p>

<p>
  <strong>Image:</strong>
  <%= @list.image %>
</p>

<p>
  <strong>Status:</strong>
  <%= @list.status %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @list.slug %>
</p>

<p>
  <strong>Board:</strong>
  <%= @list.board %>
</p>

<%= link_to 'Edit', list_path(@list) %> |