config/routes.rb
Rails.application.routes.draw do
  resources :about, only: [:index]
  
  resources :lists, only: [] do
    member do
      patch :move
    end
  end
  resources :cards, only: [:create, :update] do
    member do
      patch :move
    end
  end
  resources :boards do
    resources :lists, shallow: true, only: [:create, :destroy] do
      resources :cards, shallow: true, only: [:destroy] do
        # resources :notes, shallow: true, only: [:create, :destroy, :update]
        # resources :tasks, shallow: true, only: [:create, :destroy, :update]
      end
    end
  end
  resources :people

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/client/', to: "client#index", via: :all
  match '/client/*path', to: "client#index", via: :all

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :boards do
        resources :lists, only: [:create, :destroy, :update]
      end
      resources :users, only: [:index, :show,:create,:destroy]
      resources :tokens, only: [:create]
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  acts_as_list scope: :list

  belongs_to :list

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history, :finders]

  scope :sorted, -> { order(position: :asc, updated_at: :desc)}
  validates :name, presence: true
end

app/controllers/cards_controller.rb
class CardsController < InheritedResources::Base
  before_action :set_card, only: [:show, :edit, :update, :destroy, :move]

  def index
    @cards = current_user.cards.sorted
  end

  def show
  end

  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save

        ActionCable.server.broadcast "board", { commit: 'addCard', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @card.update(card_params)

        ActionCable.server.broadcast "board", { commit: 'editCard', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @card.update(card_params)
    ActionCable.server.broadcast "board", { commit: 'moveCard', payload: render_to_string(:show, format: :json) }
    render action: :show
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:name, :position, :slug, :list_id, :background_color, :status, :description, :job_position, :url, :font, :location, :salary, :salary_currency, :salary_period, :employment_type, :work_hours, :time_commute, :distance_commute, :resume_file, :cover_letter, :accept_remote, :date_posted, :due_date, :education_requirements, :language_requeriments, :experience_requirements, :responsabilities, :qualifications, :skills, :incentive_compensation, :benefits)
    end
end

app/views/cards/_form.html.erb
<%= semantic_form_for @card do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :position %>
    <%= f.input :slug %>
    <%= f.input :list %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Slug</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.position %></td>
        <td><%= card.slug %></td>
        <td><%= card.list %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @card.position %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @card.slug %>
</p>

<p>
  <strong>List:</strong>
  <%= @card.list %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>