config/routes.rb
Rails.application.routes.draw do
  resources :about, only: [:index]
  
  resources :lists, only: [] do
    member do
      patch :move
    end
  end
  resources :cards, only: [:create, :update] do
    member do
      patch :move
    end
  end
  resources :boards do
    resources :lists, shallow: true, only: [:create, :destroy] do
      resources :cards, shallow: true, only: [:destroy] do
        # resources :notes, shallow: true, only: [:create, :destroy, :update]
        # resources :tasks, shallow: true, only: [:create, :destroy, :update]
      end
    end
  end
  resources :people

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    omniauth_callbacks: 'user/omniauth_callbacks'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/client/', to: "client#index", via: :all
  match '/client/*path', to: "client#index", via: :all

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :boards do
        resources :lists, only: [:create, :destroy, :update]
      end
      resources :users, only: [:index, :show,:create,:destroy]
      resources :tokens, only: [:create]
    end
  end
end

app/views/layouts/application-react.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>[Rails] Get a Job</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%=
      tag.div(
        id: "Navigation"
      )
    %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <link rel="icon" href="/assets/favicon.ico">
    <title>Get a Job</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="homeMain">
      <nav class="homeNavBar navbar navbar-dark bg-transparent">
        <a href="/" class="btn btn-menu btn-custom btn-sm">Home</a>
        <a href="/about" class="btn btn-menu btn-custom btn-sm">About</a>
      </nav>
    <div class="container" id="homeContent">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/layouts/board.html.erb
<!doctype html>
<html lang="en">
  <head>
    <link rel="icon" href="/assets/favicon.ico">
    <title>Get a Job</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag     'application', media: 'all' %>
    <%= javascript_include_tag  'application' %>
    <%= stylesheet_pack_tag     'application', media: 'all' %>
    <%= javascript_pack_tag     'application' %>
  </head>

  <body class="bg-light">

    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-custom">
      <div class="container-fluid">
      <% if user_signed_in? %>
        <form class="form-inline my-2 my-lg-0 form-search">
          <div class="input-group mb-2">
            <a class="btn btn-sm btn-outline-light btn-menu" href="<%= boards_path %>">All Boards</a>
          </div>
          <div class="input-group mb-2">
            <input class="form-control btn-sm mr-sm-2" type="text" size="16" id="inputSearch" placeholder=" &#xF002; Search" aria-label="Search">
          </div>
        </form>
      <% else %>
        <div class="input-group mb-2">
          <%= link_to 'Sign Up', new_user_registration_path, :class => "btn btn-sm btn-outline-light btn-menu" %>
          <%= link_to 'Login', new_user_session_path, :class => "btn btn-sm btn-outline-light btn-menu" %>
        </div>
      <% end %>
      <div class="navbar-collapse offcanvas-collapse justify-content-center" id="rightMenu">
        <a class="navbar-brand" href="#">Get a Job</a>
      </div>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="offcanvas-collapse" id="rightMenu">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="btn btn-sm btn-outline-light btn-menu" href="" id="dropdownCreateBoard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">New Board</a>
            <div class="dropdown-menu dropdown-menu-right shadow" aria-labelledby="dropdownCreateBoard">
              <a class="dropdown-item" href="#">
                <form novalidate="novalidate" class="form-signin my-2 p-3 bg-white rounded box-shadow" action="<%= boards_path %>" id="new_user" accept-charset="UTF-8" method="post">
                  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
                  <div class="form-label-group">
                    <input type="text" size="24" id="board_name" name="board[name]" class="form-control" placeholder="Board Name" required autofocus>
                    <label for="board_name">Board Name</label>
                  </div>
                  <button class="btn btn-custom btn-block" type="submit">Create board</button>
                </form>
              </a>
            </div>
          </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="btn btn-sm btn-outline-light btn-menu" href="" id="dropdownInfo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Info</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownInfo">
              <a class="dropdown-item" href="<%= about_index_path %>">About</a>
              <a class="dropdown-item" href="">Legal</a>
              <a class="dropdown-item" href="">Contact</a>
            </div>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="" id="dropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img class="profile-photo" src="https://media.licdn.com/mpr/mprx/0_1J2xFlwQPHk7aArdJJZtW_5b12M7ahhkJJZAGXbQApTawrAkzjqO8vdQzMwyDGu5vjsluhE6xxomHkjd0Ed_f5woVxofHXveJEdyXkYFAY0_G-mqvRx-krK9sor0TXGMKdSP_sB-yCo" alt="Gustavo Parolin"> </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownProfile">
              <a class="dropdown-item" href="<%= edit_user_registration_path %>">Profile</a>
              <a class="dropdown-item" href="#">Settings</a>
              <div class="dropdown-divider"></div>
              <%= link_to('Sign Out', destroy_user_session_path, method: :delete, :class => "dropdown-item") %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    </nav>

    <main role="main" class="container-fluid space">
      <% if flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <% if flash[:notice].present? %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="/assets/favicon.ico">
    <title>789 [React] Get a Job</title>
    <%= csrf_meta_tags %>
  </head>
  <script type="text/javascript">
    console.log('layout client');
  </script>
  <body>
    <%= yield %>
</body>
</html>